shoping/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^home/',views.home,name="home"),
    url(r'^market/$',views.market,name="market"),
    url(r'^cart/',views.cart,name="cart"),
    url(r'^mine/',views.mine,name="mine"),

    url(r'^market/(\d+)/(\d+)/(\d+)',views.marketWithParam,name="market_param"),
    url(r'^register/',views.register,name="register"),
    url(r'^checkUser/',views.checkUser), #检查用户名唯一性的
    url(r'^login/',views.login,name="login"),
    url(r'^logout/',views.loginOut,name="loginout"),
    url(r'^addToCart/',views.addToCart,name="addToCart"),
    url(r'^subToCart/',views.subToCart,name="subToCart"),
    url(r'^addCart/',views.addCart,name="addCart"),
    url(r'^subCart/',views.subCart,name="subCart"),
    url(r'^chanageSelect/',views.chanageSelect,name="chanageSelect"),
    url(r'^changeManySelect/',views.changeManySelect,name="changeManySelect"),
    url(r'^createOrder/',views.createOrder,name="createOrder"),
    url(r'^orderInfo/(.+)',views.orderInfo,name="orderInfo"),
    url(r'^changeOrderStatu',views.changeOrderStatu,name="changeOrderStatu"),
]

shoping/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app.urls",namespace="axf")),
]

shoping/templates/market/market.html
{% extends 'base_main.html' %}


{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}
{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/market/market.js' %}"></script>
{% endblock %}






{% block content %}
      <div id="market">
        <aside>
            <ul>
               {% for foodtype in foodtypes %}
                   {% ifequal foodtype.typeid currentType %}
                       <li>
                           <span class="yellowSlide"></span>
                           <a href="{% url 'axf:market_param' foodtype.typeid  0 0%}">{{ foodtype.typename }}</a></li>
                       {% else %}
                       <li><a href="{% url 'axf:market_param' foodtype.typeid 0 0%}">{{ foodtype.typename }}</a></li>
                   {% endifequal %}
               {% endfor %}
            </ul>

        </aside>
        <section>
            <nav>
                <ul>
                    <li>
                        <span id="alltypes">全部分类<span id="glyphiconTypes" class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                     <li>
                        <span id="allsort">综合排序<span  id="glyphiconSort" class="glyphicon glyphicon-chevron-down"></span></span>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    {% for goods in goodall %}
                        <li>
                            <a href="">
                                <img src="{{ goods.productimg }}" alt="{{ goods.productname }}">
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <span class="unit">{{ goods.specifics }}</span>
                                    <p class="price">
                                        <span>￥{{ goods.price }}</span>
                                        <s>￥{{ goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>
                            <section>
                                <button goodsid="{{ goods.id }}" class="subToCart">-</button>
                                <span>0</span>
                                <button goodsid="{{ goods.id }}" class="addToCart">+</button>

                            </section>
                        </li>
                    {% endfor %}
                </ul>
                <div id="type_container">
                    <div>
{#                        <a href="#"><span>全部分类</span></a>#}
                          {% for childNameAndId in childNameAndIds %}
                              <a href="{% url 'axf:market_param' currentType  childNameAndId.1  0%}"><span>{{ childNameAndId.0 }}</span></a>
                          {% endfor %}
                        
                    </div>
                </div>
                <div id="allsortrule">
                    <div>
                        <a href="{% url 'axf:market_param' currentType  currentChildid  0%}"><span>综合排序</span></a>
                        <a href="{% url 'axf:market_param' currentType  currentChildid  1%}"><span>销量排序</span></a>
                        <a href="{% url 'axf:market_param' currentType  currentChildid  2%}"><span>价格降序</span></a>
                        <a href="{% url 'axf:market_param' currentType  currentChildid  3%}"><span>价格升序</span></a>
                    </div>
                </div>
            </menu>
        </section>

     </div>

{% endblock %}