shoping/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^home/',views.home,name="home"),
    url(r'^market/$',views.market,name="market"),
    url(r'^cart/',views.cart,name="cart"),
    url(r'^mine/',views.mine,name="mine"),

    url(r'^market/(\d+)/(\d+)/(\d+)',views.marketWithParam,name="market_param"),
    url(r'^register/',views.register,name="register"),
    url(r'^checkUser/',views.checkUser), #检查用户名唯一性的
    url(r'^login/',views.login,name="login"),
    url(r'^logout/',views.loginOut,name="loginout"),
    url(r'^addToCart/',views.addToCart,name="addToCart"),
    url(r'^subToCart/',views.subToCart,name="subToCart"),
    url(r'^addCart/',views.addCart,name="addCart"),
    url(r'^subCart/',views.subCart,name="subCart"),
    url(r'^chanageSelect/',views.chanageSelect,name="chanageSelect"),
    url(r'^changeManySelect/',views.changeManySelect,name="changeManySelect"),
    url(r'^createOrder/',views.createOrder,name="createOrder"),
    url(r'^orderInfo/(.+)',views.orderInfo,name="orderInfo"),
    url(r'^changeOrderStatu',views.changeOrderStatu,name="changeOrderStatu"),
]

shoping/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app.urls",namespace="axf")),
]

shoping/templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0" />
    <title> {% block title %}{% endblock %}</title>
{#    导入通用css  #}
{#    <link rel="stylesheet" href="{% static '' %}">#}
     <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
     <link href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet">
     <link rel="stylesheet" href="{%  static 'css/reset.css' %}">
     {% block extCSS %}
{#        挖坑, 用于扩展css#}
     {% endblock %}
</head>
<body>
{#   将页面划分成多块#}
    {% block head %}
{#        放头的#}
    
    {% endblock %}

    {% block content %}
{#        放内容的#}
    
    {% endblock %}

    {% block foot %}
{#        放脚的#}
    
    {% endblock %}


    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.js"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
   {% block extJS %}
{#       挖坑,用于扩展js#}
   {% endblock %}
</body>
</html>

shoping/templates/base_main.html
{#继承#}
{% extends "base.html" %}
{% load static %}



{#引入该HTML对应的css#}

{% block extCSS %}
   {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/base_main.css'%}">
{% endblock %}




{#填坑#}

{% block head %}
{#    头#}
    <header>

    </header>

{% endblock %}


{% block foot %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购</dd>
            </dl>
        </a>
       <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>

{% endblock %}